namespace: zp4rker
name: azure
version: 1.0.0

readme: README.md

authors:
- Zaeem Parker <iam@zp4rker.com>

description: Sending events to Azure EventHub using Ansible.

repository: https://github.com/zp4rker/ansible-azure
